const CUT_AUTHORS_NAME_LENGTH = 30;
const BUTTON_TEXT_SHOW_COURSE = 'Show Course';
const BUTTON_TEXT_SEARCH = 'Search';
const BUTTON_TEXT_CREATE_AUTHOR = 'Create author';
const BUTTON_TEXT_ADD_NEW_COURSE = 'Add new course';
const BUTTON_TEXT_ADD_AUTHORS = 'Add Authors';
const BUTTON_TEXT_DELETE_AUTHORS = 'Delete Authors';
const TYPE_INPUT_TEXT = 'text';
const TYPE_INPUT_NUMBER = 'number';
const NAME_INPUT_TEXT = 'text';
export {
	CUT_AUTHORS_NAME_LENGTH,
	BUTTON_TEXT_SHOW_COURSE,
	BUTTON_TEXT_SEARCH,
	BUTTON_TEXT_ADD_NEW_COURSE,
	TYPE_INPUT_TEXT,
	NAME_INPUT_TEXT,
	TYPE_INPUT_NUMBER,
	BUTTON_TEXT_CREATE_AUTHOR,
	BUTTON_TEXT_ADD_AUTHORS,
	BUTTON_TEXT_DELETE_AUTHORS,
};
